from . import farm_land
from . import farm_zone
from . import farm_stage
from . import farm_job
from . import farm_job_line
from . import farm_job_operation
from . import farm_produce_quality
from . import farmer_team
from . import hr_employee
from . import ir_actions_report