{
    'name': 'Customer Credit Limit With Warning and Blocking',
    'author': 'DuyBQ',
    'category': 'Accounting',
    'version': '1.0.1',
    'description': """Customer Credit Limit, Credit Limit With Warning and Blocking, Customer Credit Limit With Warning and Blocking""",
    'summary': """Customer Credit Limit, Credit Limit With Warning and Blocking, Customer Credit Limit With Warning and Blocking""",
    'sequence': 11,
    'website': 'https://www.odoobase.com/',
    'depends': [
        'account',
        'sale',
        'odb_account_accountant',
    ],
    'data': [
        'views/res_partner.xml',
        'views/account_move.xml',
        'views/sale_order.xml',
        'views/res_config_settings.xml',
    ],
    'license': 'OPL-1',
    'installable': True,
    'application': False,
    'auto_install': False,
}
