# -*- coding: utf-8 -*-
{
    'name': 'Account Accountant',
    'version': '1.0.1',
    'category': 'Accounting',
    'summary': """ Asset and Budget Management,
                 Accounting Reports, PDC,
                 Credit Limit, Follow Ups,
                 Day-Bank-Cash book reports.""",
    'description': """
                    PDF Reports, Asset Management, Budget Management,
                    Customer Credit Limit, Recurring Payment,
                    PDC Management, Customer Follow-up,
                    Full Accounting Package,
                    Financial Reports,
                    Reconciliation Widget,
                    Payments Matching
                    """,
    'author': 'DuyBQ',
    'website': "https://www.odoobase.com/",
    'depends': [
        'base',
        'account',
        'sale',
        'account_payment',
        'account_check_printing',
        'odb_account_budget',
        'odb_account_asset',
        'odb_account_reports_pdf',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups.xml',

        'data/account_financial_report_data.xml',
        'data/account_pdc_data.xml',
        'data/recurring_entry_cron.xml',
        'data/multiple_invoice_data.xml',
        'data/ir_actions_report.xml',

        'wizard/financial_report.xml',

        'report/multiple_invoice_layouts.xml',
        'report/multiple_invoice_report.xml',
        
        'views/account_move_views.xml',
        'views/dashboard_views.xml',
        'views/account_group.xml',
        'views/credit_limit_view.xml',
        'views/account_payment_view.xml',
        'views/recurring_payments_view.xml',
        'views/followup_report.xml',
        'views/payment_matching.xml',
        'views/multiple_invoice_layout_view.xml',
        'views/multiple_invoice_form.xml',
        'views/account_account_views.xml',
        'views/res_config_view.xml',
        'views/menu_views.xml',

        'mail/bill_mail_template.xml',
        'mail/invoice_mail_template.xml',
        'mail/payment_mail_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'odb_account_accountant/static/src/scss/style.scss',
            'odb_account_accountant/static/lib/bootstrap-toggle-master/css/bootstrap-toggle.min.css',
            'odb_account_accountant/static/src/js/account_dashboard.js',
            'odb_account_accountant/static/src/js/payment_model.js',
            'odb_account_accountant/static/src/js/payment_render.js',
            'odb_account_accountant/static/src/js/payment_matching.js',
            'odb_account_accountant/static/lib/Chart.bundle.js',
            'odb_account_accountant/static/lib/Chart.bundle.min.js',
            'odb_account_accountant/static/lib/Chart.min.js',
            'odb_account_accountant/static/lib/Chart.js',
            'odb_account_accountant/static/lib/bootstrap-toggle-master/js/bootstrap-toggle.min.js',

        ],
        'web.assets_qweb': [
            'odb_account_accountant/static/src/xml/template.xml',
            'odb_account_accountant/static/src/xml/payment_matching.xml',
        ],
    },
    'license': 'OPL-1',
    'installable': True,
    'application': True,
    'auto_install': False,
}
